
# YML stands YET ANOTHER MARKUP Language




spring:
  application:
    name: P47-Properties-files-Value
server:
  port: 3333
main:
  fullform: YML stands YET ANOTHER MARKUP Language.....
messages:
  word: welcome to properties.........!!
babu:
  balayya: 游때游때游때游때游때 balayya babu fan eakkada...............仇벒잺!!